-- Number of Retiring Employees
SELECT COUNT(*) FROM EMPLOYEES
WHERE BIRTH_DATE BETWEEN '1952-01-01' AND '1955-12-31'
AND HIRE_DATE BETWEEN '1985-01-01' AND '1988-12-31';
-- 41380

-- Saving the Retiring Employee Info in a table
SELECT EMP_NO, FIRST_NAME, LAST_NAME
INTO RETIREMENT_INFO
FROM EMPLOYEES
WHERE BIRTH_DATE BETWEEN '1952-01-01' AND '1955-12-31'
AND HIRE_DATE BETWEEN '1985-01-01' AND '1988-12-31';

SELECT 
	DEPT.DEPT_NAME AS DEPARTMENT,
	RE.FIRST_NAME AS FIRST_NAME,
	RE.LAST_NAME AS LAST_NAME
FROM RETIREMENT_INFO RE
LEFT JOIN DEPT_EMP DE
ON RE.EMP_NO = DE.EMP_NO
INNER JOIN DEPARTMENTS DEPT
ON DE.DEPT_NO = DEPT.DEPT_NO
WHERE DE.TO_DATE = '9999-01-01'
GROUP BY DEPARTMENT, FIRST_NAME, LAST_NAME;

-- Count of Retiring Employees by Department
SELECT 
DEPT.DEPT_NAME AS "DEPARTMENT",
COUNT(DE.EMP_NO) AS "NUMBER OF RETIRING EMPLOYEES"
FROM RETIREMENT_INFO RE
LEFT JOIN DEPT_EMP DE
ON RE.EMP_NO = DE.EMP_NO
LEFT JOIN DEPARTMENTS DEPT
ON DE.DEPT_NO = DEPT.DEPT_NO
WHERE DE.TO_DATE = '9999-01-01'
GROUP BY "DEPARTMENT"

-- Employee Information: A list of employees containing their unique employee number, their last name, 
--first name, gender, and salary
SELECT
EMP.EMP_NO AS "EMPLOYEE ID",
EMP.LAST_NAME AS "LAST NAME",
EMP.FIRST_NAME AS "FIRST NAME",
EMP.GENDER AS "GENDER",
SAL.SALARY AS "SALARY"
INTO EMP_INFO
FROM EMPLOYEES EMP
JOIN DEPT_EMP DE
ON EMP.EMP_NO = DE.EMP_NO
LEFT JOIN SALARIES SAL
ON EMP.EMP_NO = SAL.EMP_NO
WHERE BIRTH_DATE BETWEEN '1952-01-01' AND '1955-12-31'
AND HIRE_DATE BETWEEN '1985-01-01' AND '1988-12-31'
AND DE.TO_DATE = '9999-01-01'
ORDER BY 1;

-- Management: A list of managers for each department, including the department number, name, 
-- and the manager's employee number, last name, first name, and the starting and ending employment dates
SELECT 
DEPT.DEPT_NO AS "DEPARTMENT ID",
DEPT.DEPT_NAME AS "DEPARTMENT NAME",
DM.EMP_NO AS "EMPLOYEE ID",
EMP.LAST_NAME AS "LAST NAME",
EMP.FIRST_NAME AS "FIRST NAME",
EMP.HIRE_DATE AS "EMPLOYMENT START DATE",
DM.TO_DATE AS "EMPLOYMENT END DATE"
INTO MANAGER_INFO
FROM DEPT_MANAGER DM
JOIN DEPARTMENTS DEPT
ON DM.DEPT_NO = DEPT.DEPT_NO
JOIN EMPLOYEES EMP
ON DM.EMP_NO = EMP.EMP_NO
JOIN DEPT_EMP DE
ON DM.EMP_NO = DE.EMP_NO
WHERE DM.TO_DATE = '9999-01-01';
		
-- Department Retirees: An updated current_emp list that includes everything it currently has, 
-- but also the employee's departments
SELECT 
EMP.EMP_NO AS "EMPLOYEE NUMBER",
EMP.FIRST_NAME AS "FIRST NAME",
EMP.LAST_NAME AS "LAST NAME",
DEPT.DEPT_NAME AS "DEPARTMENT"
INTO DEPT_INFO
FROM EMPLOYEES EMP
LEFT JOIN DEPT_EMP DE
ON EMP.EMP_NO = DE.EMP_NO
LEFT JOIN DEPARTMENTS DEPT
ON DE.DEPT_NO = DEPT.DEPT_NO
WHERE BIRTH_DATE BETWEEN '1952-01-01' AND '1955-12-31'
AND HIRE_DATE BETWEEN '1985-01-01' AND '1988-12-31'
AND DE.TO_DATE = '9999-01-01';

-- Retiring Employees from Sales Department
SELECT
RI.EMP_NO,
RI.FIRST_NAME,
RI.LAST_NAME,
DEPT.DEPT_NAME
FROM RETIREMENT_INFO RI
JOIN DEPT_EMP DE
ON RI.EMP_NO = DE.EMP_NO
JOIN DEPARTMENTS DEPT
ON DE.DEPT_NO = DEPT.DEPT_NO
WHERE DE.TO_DATE = '9999-01-01'
AND DEPT.DEPT_NAME IN ('Sales','Development');
