--***************************************************************************
-- Deliverable 1.1: Retirement Titles
SELECT 
EMP.EMP_NO,
EMP.FIRST_NAME,
EMP.LAST_NAME,
T.TITLE,
T.FROM_DATE,
T.TO_DATE
INTO RETIREMENT_TITLES
FROM EMPLOYEES EMP
JOIN TITLES T
ON EMP.EMP_NO = T.EMP_NO
WHERE BIRTH_DATE BETWEEN '1952-01-01' AND '1955-12-31'
ORDER BY EMP_NO;

-- Deliverable 1.2: Unique Titles
SELECT 
DISTINCT ON (EMP_NO)
EMP_NO,
FIRST_NAME,
LAST_NAME,
TITLE
INTO UNIQUE_TITLES
FROM RETIREMENT_TITLES
ORDER BY EMP_NO, TO_DATE DESC;

-- Deliverable 1.3: Retiring Titles
SELECT 
TITLE AS "TITLE",
COUNT(EMP_NO) AS "RETIRING EMPLOYEES"
INTO RETIRING_TITLES
FROM UNIQUE_TITLES
GROUP BY "TITLE"
ORDER BY "RETIRING EMPLOYEES" DESC;

--***************************************************************************

-- Deliverable 2: Mentorship Eligibility
SELECT 
DISTINCT ON (EMP_NO)
EMP.EMP_NO,
EMP.FIRST_NAME,
EMP.LAST_NAME,
EMP.BIRTH_DATE,
DE.FROM_DATE,
DE.TO_DATE,
T.TITLE
INTO MENTORSHIP_ELIGIBILITY
FROM EMPLOYEES EMP
JOIN DEPT_EMP DE
ON EMP.EMP_NO = DE.EMP_NO
JOIN TITLES T
ON EMP.EMP_NO = T.EMP_NO
WHERE DE.TO_DATE = '9999-01-01'
AND BIRTH_DATE BETWEEN '1965-01-01' AND '1965-12-31'
ORDER BY EMP_NO,T.TO_DATE DESC;

SELECT * FROM TITLES WHERE EMP_NO='10291';